# Site settings
title: Alex Ji
email: aji at carnegiescience dot edu
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://alexji.github.io" # the base hostname & protocol for your site
twitter_username: alexanderpji
github_username:  alexji

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight

